// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vehicle_gateway.proto
#ifndef GRPC_vehicle_5fgateway_2eproto__INCLUDED
#define GRPC_vehicle_5fgateway_2eproto__INCLUDED

#include "vehicle_gateway.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace vehicle_gateway {

class VehicleGateway final {
 public:
  static constexpr char const* service_full_name() {
    return "vehicle_gateway.VehicleGateway";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendEta(::grpc::ClientContext* context, const ::vehicle_gateway::EtaRequest& request, ::vehicle_gateway::EtaResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::EtaResponse>> AsyncSendEta(::grpc::ClientContext* context, const ::vehicle_gateway::EtaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::EtaResponse>>(AsyncSendEtaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::EtaResponse>> PrepareAsyncSendEta(::grpc::ClientContext* context, const ::vehicle_gateway::EtaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::EtaResponse>>(PrepareAsyncSendEtaRaw(context, request, cq));
    }
    virtual ::grpc::Status SendStatus(::grpc::ClientContext* context, const ::vehicle_gateway::StatusRequest& request, ::vehicle_gateway::StatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::StatusResponse>> AsyncSendStatus(::grpc::ClientContext* context, const ::vehicle_gateway::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::StatusResponse>>(AsyncSendStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::StatusResponse>> PrepareAsyncSendStatus(::grpc::ClientContext* context, const ::vehicle_gateway::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::StatusResponse>>(PrepareAsyncSendStatusRaw(context, request, cq));
    }
    virtual ::grpc::Status SendArrive(::grpc::ClientContext* context, const ::vehicle_gateway::ArriveRequest& request, ::vehicle_gateway::ArriveResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::ArriveResponse>> AsyncSendArrive(::grpc::ClientContext* context, const ::vehicle_gateway::ArriveRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::ArriveResponse>>(AsyncSendArriveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::ArriveResponse>> PrepareAsyncSendArrive(::grpc::ClientContext* context, const ::vehicle_gateway::ArriveRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::ArriveResponse>>(PrepareAsyncSendArriveRaw(context, request, cq));
    }
    virtual ::grpc::Status UpdateVehicleLocation(::grpc::ClientContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest& request, ::vehicle_gateway::UpdateVehicleLocationResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::UpdateVehicleLocationResponse>> AsyncUpdateVehicleLocation(::grpc::ClientContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::UpdateVehicleLocationResponse>>(AsyncUpdateVehicleLocationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::UpdateVehicleLocationResponse>> PrepareAsyncUpdateVehicleLocation(::grpc::ClientContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::UpdateVehicleLocationResponse>>(PrepareAsyncUpdateVehicleLocationRaw(context, request, cq));
    }
    virtual ::grpc::Status TripInit(::grpc::ClientContext* context, const ::vehicle_gateway::TripInitRequest& request, ::vehicle_gateway::TripInitResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::TripInitResponse>> AsyncTripInit(::grpc::ClientContext* context, const ::vehicle_gateway::TripInitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::TripInitResponse>>(AsyncTripInitRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::TripInitResponse>> PrepareAsyncTripInit(::grpc::ClientContext* context, const ::vehicle_gateway::TripInitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::TripInitResponse>>(PrepareAsyncTripInitRaw(context, request, cq));
    }
    virtual ::grpc::Status TripMove(::grpc::ClientContext* context, const ::vehicle_gateway::TripMoveRequest& request, ::vehicle_gateway::TripMoveResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::TripMoveResponse>> AsyncTripMove(::grpc::ClientContext* context, const ::vehicle_gateway::TripMoveRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::TripMoveResponse>>(AsyncTripMoveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::TripMoveResponse>> PrepareAsyncTripMove(::grpc::ClientContext* context, const ::vehicle_gateway::TripMoveRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::TripMoveResponse>>(PrepareAsyncTripMoveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>> VehicleCommandStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>>(VehicleCommandStreamRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>> AsyncVehicleCommandStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>>(AsyncVehicleCommandStreamRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>> PrepareAsyncVehicleCommandStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>>(PrepareAsyncVehicleCommandStreamRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendEta(::grpc::ClientContext* context, const ::vehicle_gateway::EtaRequest* request, ::vehicle_gateway::EtaResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendEta(::grpc::ClientContext* context, const ::vehicle_gateway::EtaRequest* request, ::vehicle_gateway::EtaResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SendStatus(::grpc::ClientContext* context, const ::vehicle_gateway::StatusRequest* request, ::vehicle_gateway::StatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendStatus(::grpc::ClientContext* context, const ::vehicle_gateway::StatusRequest* request, ::vehicle_gateway::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SendArrive(::grpc::ClientContext* context, const ::vehicle_gateway::ArriveRequest* request, ::vehicle_gateway::ArriveResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendArrive(::grpc::ClientContext* context, const ::vehicle_gateway::ArriveRequest* request, ::vehicle_gateway::ArriveResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void UpdateVehicleLocation(::grpc::ClientContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest* request, ::vehicle_gateway::UpdateVehicleLocationResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateVehicleLocation(::grpc::ClientContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest* request, ::vehicle_gateway::UpdateVehicleLocationResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void TripInit(::grpc::ClientContext* context, const ::vehicle_gateway::TripInitRequest* request, ::vehicle_gateway::TripInitResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void TripInit(::grpc::ClientContext* context, const ::vehicle_gateway::TripInitRequest* request, ::vehicle_gateway::TripInitResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void TripMove(::grpc::ClientContext* context, const ::vehicle_gateway::TripMoveRequest* request, ::vehicle_gateway::TripMoveResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void TripMove(::grpc::ClientContext* context, const ::vehicle_gateway::TripMoveRequest* request, ::vehicle_gateway::TripMoveResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void VehicleCommandStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::vehicle_gateway::VehicleEvent,::vehicle_gateway::GatewayCommand>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::EtaResponse>* AsyncSendEtaRaw(::grpc::ClientContext* context, const ::vehicle_gateway::EtaRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::EtaResponse>* PrepareAsyncSendEtaRaw(::grpc::ClientContext* context, const ::vehicle_gateway::EtaRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::StatusResponse>* AsyncSendStatusRaw(::grpc::ClientContext* context, const ::vehicle_gateway::StatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::StatusResponse>* PrepareAsyncSendStatusRaw(::grpc::ClientContext* context, const ::vehicle_gateway::StatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::ArriveResponse>* AsyncSendArriveRaw(::grpc::ClientContext* context, const ::vehicle_gateway::ArriveRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::ArriveResponse>* PrepareAsyncSendArriveRaw(::grpc::ClientContext* context, const ::vehicle_gateway::ArriveRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::UpdateVehicleLocationResponse>* AsyncUpdateVehicleLocationRaw(::grpc::ClientContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::UpdateVehicleLocationResponse>* PrepareAsyncUpdateVehicleLocationRaw(::grpc::ClientContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::TripInitResponse>* AsyncTripInitRaw(::grpc::ClientContext* context, const ::vehicle_gateway::TripInitRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::TripInitResponse>* PrepareAsyncTripInitRaw(::grpc::ClientContext* context, const ::vehicle_gateway::TripInitRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::TripMoveResponse>* AsyncTripMoveRaw(::grpc::ClientContext* context, const ::vehicle_gateway::TripMoveRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vehicle_gateway::TripMoveResponse>* PrepareAsyncTripMoveRaw(::grpc::ClientContext* context, const ::vehicle_gateway::TripMoveRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>* VehicleCommandStreamRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>* AsyncVehicleCommandStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>* PrepareAsyncVehicleCommandStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendEta(::grpc::ClientContext* context, const ::vehicle_gateway::EtaRequest& request, ::vehicle_gateway::EtaResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::EtaResponse>> AsyncSendEta(::grpc::ClientContext* context, const ::vehicle_gateway::EtaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::EtaResponse>>(AsyncSendEtaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::EtaResponse>> PrepareAsyncSendEta(::grpc::ClientContext* context, const ::vehicle_gateway::EtaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::EtaResponse>>(PrepareAsyncSendEtaRaw(context, request, cq));
    }
    ::grpc::Status SendStatus(::grpc::ClientContext* context, const ::vehicle_gateway::StatusRequest& request, ::vehicle_gateway::StatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::StatusResponse>> AsyncSendStatus(::grpc::ClientContext* context, const ::vehicle_gateway::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::StatusResponse>>(AsyncSendStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::StatusResponse>> PrepareAsyncSendStatus(::grpc::ClientContext* context, const ::vehicle_gateway::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::StatusResponse>>(PrepareAsyncSendStatusRaw(context, request, cq));
    }
    ::grpc::Status SendArrive(::grpc::ClientContext* context, const ::vehicle_gateway::ArriveRequest& request, ::vehicle_gateway::ArriveResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::ArriveResponse>> AsyncSendArrive(::grpc::ClientContext* context, const ::vehicle_gateway::ArriveRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::ArriveResponse>>(AsyncSendArriveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::ArriveResponse>> PrepareAsyncSendArrive(::grpc::ClientContext* context, const ::vehicle_gateway::ArriveRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::ArriveResponse>>(PrepareAsyncSendArriveRaw(context, request, cq));
    }
    ::grpc::Status UpdateVehicleLocation(::grpc::ClientContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest& request, ::vehicle_gateway::UpdateVehicleLocationResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::UpdateVehicleLocationResponse>> AsyncUpdateVehicleLocation(::grpc::ClientContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::UpdateVehicleLocationResponse>>(AsyncUpdateVehicleLocationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::UpdateVehicleLocationResponse>> PrepareAsyncUpdateVehicleLocation(::grpc::ClientContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::UpdateVehicleLocationResponse>>(PrepareAsyncUpdateVehicleLocationRaw(context, request, cq));
    }
    ::grpc::Status TripInit(::grpc::ClientContext* context, const ::vehicle_gateway::TripInitRequest& request, ::vehicle_gateway::TripInitResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::TripInitResponse>> AsyncTripInit(::grpc::ClientContext* context, const ::vehicle_gateway::TripInitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::TripInitResponse>>(AsyncTripInitRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::TripInitResponse>> PrepareAsyncTripInit(::grpc::ClientContext* context, const ::vehicle_gateway::TripInitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::TripInitResponse>>(PrepareAsyncTripInitRaw(context, request, cq));
    }
    ::grpc::Status TripMove(::grpc::ClientContext* context, const ::vehicle_gateway::TripMoveRequest& request, ::vehicle_gateway::TripMoveResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::TripMoveResponse>> AsyncTripMove(::grpc::ClientContext* context, const ::vehicle_gateway::TripMoveRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::TripMoveResponse>>(AsyncTripMoveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::TripMoveResponse>> PrepareAsyncTripMove(::grpc::ClientContext* context, const ::vehicle_gateway::TripMoveRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::TripMoveResponse>>(PrepareAsyncTripMoveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>> VehicleCommandStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>>(VehicleCommandStreamRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>> AsyncVehicleCommandStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>>(AsyncVehicleCommandStreamRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>> PrepareAsyncVehicleCommandStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>>(PrepareAsyncVehicleCommandStreamRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendEta(::grpc::ClientContext* context, const ::vehicle_gateway::EtaRequest* request, ::vehicle_gateway::EtaResponse* response, std::function<void(::grpc::Status)>) override;
      void SendEta(::grpc::ClientContext* context, const ::vehicle_gateway::EtaRequest* request, ::vehicle_gateway::EtaResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SendStatus(::grpc::ClientContext* context, const ::vehicle_gateway::StatusRequest* request, ::vehicle_gateway::StatusResponse* response, std::function<void(::grpc::Status)>) override;
      void SendStatus(::grpc::ClientContext* context, const ::vehicle_gateway::StatusRequest* request, ::vehicle_gateway::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SendArrive(::grpc::ClientContext* context, const ::vehicle_gateway::ArriveRequest* request, ::vehicle_gateway::ArriveResponse* response, std::function<void(::grpc::Status)>) override;
      void SendArrive(::grpc::ClientContext* context, const ::vehicle_gateway::ArriveRequest* request, ::vehicle_gateway::ArriveResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void UpdateVehicleLocation(::grpc::ClientContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest* request, ::vehicle_gateway::UpdateVehicleLocationResponse* response, std::function<void(::grpc::Status)>) override;
      void UpdateVehicleLocation(::grpc::ClientContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest* request, ::vehicle_gateway::UpdateVehicleLocationResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void TripInit(::grpc::ClientContext* context, const ::vehicle_gateway::TripInitRequest* request, ::vehicle_gateway::TripInitResponse* response, std::function<void(::grpc::Status)>) override;
      void TripInit(::grpc::ClientContext* context, const ::vehicle_gateway::TripInitRequest* request, ::vehicle_gateway::TripInitResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void TripMove(::grpc::ClientContext* context, const ::vehicle_gateway::TripMoveRequest* request, ::vehicle_gateway::TripMoveResponse* response, std::function<void(::grpc::Status)>) override;
      void TripMove(::grpc::ClientContext* context, const ::vehicle_gateway::TripMoveRequest* request, ::vehicle_gateway::TripMoveResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void VehicleCommandStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::vehicle_gateway::VehicleEvent,::vehicle_gateway::GatewayCommand>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::EtaResponse>* AsyncSendEtaRaw(::grpc::ClientContext* context, const ::vehicle_gateway::EtaRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::EtaResponse>* PrepareAsyncSendEtaRaw(::grpc::ClientContext* context, const ::vehicle_gateway::EtaRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::StatusResponse>* AsyncSendStatusRaw(::grpc::ClientContext* context, const ::vehicle_gateway::StatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::StatusResponse>* PrepareAsyncSendStatusRaw(::grpc::ClientContext* context, const ::vehicle_gateway::StatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::ArriveResponse>* AsyncSendArriveRaw(::grpc::ClientContext* context, const ::vehicle_gateway::ArriveRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::ArriveResponse>* PrepareAsyncSendArriveRaw(::grpc::ClientContext* context, const ::vehicle_gateway::ArriveRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::UpdateVehicleLocationResponse>* AsyncUpdateVehicleLocationRaw(::grpc::ClientContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::UpdateVehicleLocationResponse>* PrepareAsyncUpdateVehicleLocationRaw(::grpc::ClientContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::TripInitResponse>* AsyncTripInitRaw(::grpc::ClientContext* context, const ::vehicle_gateway::TripInitRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::TripInitResponse>* PrepareAsyncTripInitRaw(::grpc::ClientContext* context, const ::vehicle_gateway::TripInitRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::TripMoveResponse>* AsyncTripMoveRaw(::grpc::ClientContext* context, const ::vehicle_gateway::TripMoveRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vehicle_gateway::TripMoveResponse>* PrepareAsyncTripMoveRaw(::grpc::ClientContext* context, const ::vehicle_gateway::TripMoveRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>* VehicleCommandStreamRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>* AsyncVehicleCommandStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>* PrepareAsyncVehicleCommandStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendEta_;
    const ::grpc::internal::RpcMethod rpcmethod_SendStatus_;
    const ::grpc::internal::RpcMethod rpcmethod_SendArrive_;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateVehicleLocation_;
    const ::grpc::internal::RpcMethod rpcmethod_TripInit_;
    const ::grpc::internal::RpcMethod rpcmethod_TripMove_;
    const ::grpc::internal::RpcMethod rpcmethod_VehicleCommandStream_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendEta(::grpc::ServerContext* context, const ::vehicle_gateway::EtaRequest* request, ::vehicle_gateway::EtaResponse* response);
    virtual ::grpc::Status SendStatus(::grpc::ServerContext* context, const ::vehicle_gateway::StatusRequest* request, ::vehicle_gateway::StatusResponse* response);
    virtual ::grpc::Status SendArrive(::grpc::ServerContext* context, const ::vehicle_gateway::ArriveRequest* request, ::vehicle_gateway::ArriveResponse* response);
    virtual ::grpc::Status UpdateVehicleLocation(::grpc::ServerContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest* request, ::vehicle_gateway::UpdateVehicleLocationResponse* response);
    virtual ::grpc::Status TripInit(::grpc::ServerContext* context, const ::vehicle_gateway::TripInitRequest* request, ::vehicle_gateway::TripInitResponse* response);
    virtual ::grpc::Status TripMove(::grpc::ServerContext* context, const ::vehicle_gateway::TripMoveRequest* request, ::vehicle_gateway::TripMoveResponse* response);
    virtual ::grpc::Status VehicleCommandStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::vehicle_gateway::GatewayCommand, ::vehicle_gateway::VehicleEvent>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendEta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendEta() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendEta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendEta(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::EtaRequest* /*request*/, ::vehicle_gateway::EtaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendEta(::grpc::ServerContext* context, ::vehicle_gateway::EtaRequest* request, ::grpc::ServerAsyncResponseWriter< ::vehicle_gateway::EtaResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SendStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendStatus() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SendStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendStatus(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::StatusRequest* /*request*/, ::vehicle_gateway::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendStatus(::grpc::ServerContext* context, ::vehicle_gateway::StatusRequest* request, ::grpc::ServerAsyncResponseWriter< ::vehicle_gateway::StatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SendArrive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendArrive() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_SendArrive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendArrive(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::ArriveRequest* /*request*/, ::vehicle_gateway::ArriveResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendArrive(::grpc::ServerContext* context, ::vehicle_gateway::ArriveRequest* request, ::grpc::ServerAsyncResponseWriter< ::vehicle_gateway::ArriveResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateVehicleLocation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateVehicleLocation() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_UpdateVehicleLocation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateVehicleLocation(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::UpdateVehicleLocationRequest* /*request*/, ::vehicle_gateway::UpdateVehicleLocationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateVehicleLocation(::grpc::ServerContext* context, ::vehicle_gateway::UpdateVehicleLocationRequest* request, ::grpc::ServerAsyncResponseWriter< ::vehicle_gateway::UpdateVehicleLocationResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_TripInit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_TripInit() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_TripInit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TripInit(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::TripInitRequest* /*request*/, ::vehicle_gateway::TripInitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTripInit(::grpc::ServerContext* context, ::vehicle_gateway::TripInitRequest* request, ::grpc::ServerAsyncResponseWriter< ::vehicle_gateway::TripInitResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_TripMove : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_TripMove() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_TripMove() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TripMove(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::TripMoveRequest* /*request*/, ::vehicle_gateway::TripMoveResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTripMove(::grpc::ServerContext* context, ::vehicle_gateway::TripMoveRequest* request, ::grpc::ServerAsyncResponseWriter< ::vehicle_gateway::TripMoveResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_VehicleCommandStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_VehicleCommandStream() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_VehicleCommandStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VehicleCommandStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::vehicle_gateway::GatewayCommand, ::vehicle_gateway::VehicleEvent>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVehicleCommandStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::vehicle_gateway::GatewayCommand, ::vehicle_gateway::VehicleEvent>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(6, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendEta<WithAsyncMethod_SendStatus<WithAsyncMethod_SendArrive<WithAsyncMethod_UpdateVehicleLocation<WithAsyncMethod_TripInit<WithAsyncMethod_TripMove<WithAsyncMethod_VehicleCommandStream<Service > > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendEta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendEta() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::vehicle_gateway::EtaRequest, ::vehicle_gateway::EtaResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vehicle_gateway::EtaRequest* request, ::vehicle_gateway::EtaResponse* response) { return this->SendEta(context, request, response); }));}
    void SetMessageAllocatorFor_SendEta(
        ::grpc::MessageAllocator< ::vehicle_gateway::EtaRequest, ::vehicle_gateway::EtaResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vehicle_gateway::EtaRequest, ::vehicle_gateway::EtaResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendEta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendEta(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::EtaRequest* /*request*/, ::vehicle_gateway::EtaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendEta(
      ::grpc::CallbackServerContext* /*context*/, const ::vehicle_gateway::EtaRequest* /*request*/, ::vehicle_gateway::EtaResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SendStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendStatus() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::vehicle_gateway::StatusRequest, ::vehicle_gateway::StatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vehicle_gateway::StatusRequest* request, ::vehicle_gateway::StatusResponse* response) { return this->SendStatus(context, request, response); }));}
    void SetMessageAllocatorFor_SendStatus(
        ::grpc::MessageAllocator< ::vehicle_gateway::StatusRequest, ::vehicle_gateway::StatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vehicle_gateway::StatusRequest, ::vehicle_gateway::StatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendStatus(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::StatusRequest* /*request*/, ::vehicle_gateway::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::vehicle_gateway::StatusRequest* /*request*/, ::vehicle_gateway::StatusResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SendArrive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendArrive() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::vehicle_gateway::ArriveRequest, ::vehicle_gateway::ArriveResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vehicle_gateway::ArriveRequest* request, ::vehicle_gateway::ArriveResponse* response) { return this->SendArrive(context, request, response); }));}
    void SetMessageAllocatorFor_SendArrive(
        ::grpc::MessageAllocator< ::vehicle_gateway::ArriveRequest, ::vehicle_gateway::ArriveResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vehicle_gateway::ArriveRequest, ::vehicle_gateway::ArriveResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendArrive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendArrive(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::ArriveRequest* /*request*/, ::vehicle_gateway::ArriveResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendArrive(
      ::grpc::CallbackServerContext* /*context*/, const ::vehicle_gateway::ArriveRequest* /*request*/, ::vehicle_gateway::ArriveResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_UpdateVehicleLocation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UpdateVehicleLocation() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::vehicle_gateway::UpdateVehicleLocationRequest, ::vehicle_gateway::UpdateVehicleLocationResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest* request, ::vehicle_gateway::UpdateVehicleLocationResponse* response) { return this->UpdateVehicleLocation(context, request, response); }));}
    void SetMessageAllocatorFor_UpdateVehicleLocation(
        ::grpc::MessageAllocator< ::vehicle_gateway::UpdateVehicleLocationRequest, ::vehicle_gateway::UpdateVehicleLocationResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vehicle_gateway::UpdateVehicleLocationRequest, ::vehicle_gateway::UpdateVehicleLocationResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UpdateVehicleLocation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateVehicleLocation(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::UpdateVehicleLocationRequest* /*request*/, ::vehicle_gateway::UpdateVehicleLocationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateVehicleLocation(
      ::grpc::CallbackServerContext* /*context*/, const ::vehicle_gateway::UpdateVehicleLocationRequest* /*request*/, ::vehicle_gateway::UpdateVehicleLocationResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_TripInit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_TripInit() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::vehicle_gateway::TripInitRequest, ::vehicle_gateway::TripInitResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vehicle_gateway::TripInitRequest* request, ::vehicle_gateway::TripInitResponse* response) { return this->TripInit(context, request, response); }));}
    void SetMessageAllocatorFor_TripInit(
        ::grpc::MessageAllocator< ::vehicle_gateway::TripInitRequest, ::vehicle_gateway::TripInitResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vehicle_gateway::TripInitRequest, ::vehicle_gateway::TripInitResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_TripInit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TripInit(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::TripInitRequest* /*request*/, ::vehicle_gateway::TripInitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TripInit(
      ::grpc::CallbackServerContext* /*context*/, const ::vehicle_gateway::TripInitRequest* /*request*/, ::vehicle_gateway::TripInitResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_TripMove : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_TripMove() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::vehicle_gateway::TripMoveRequest, ::vehicle_gateway::TripMoveResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vehicle_gateway::TripMoveRequest* request, ::vehicle_gateway::TripMoveResponse* response) { return this->TripMove(context, request, response); }));}
    void SetMessageAllocatorFor_TripMove(
        ::grpc::MessageAllocator< ::vehicle_gateway::TripMoveRequest, ::vehicle_gateway::TripMoveResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vehicle_gateway::TripMoveRequest, ::vehicle_gateway::TripMoveResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_TripMove() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TripMove(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::TripMoveRequest* /*request*/, ::vehicle_gateway::TripMoveResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TripMove(
      ::grpc::CallbackServerContext* /*context*/, const ::vehicle_gateway::TripMoveRequest* /*request*/, ::vehicle_gateway::TripMoveResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_VehicleCommandStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_VehicleCommandStream() {
      ::grpc::Service::MarkMethodCallback(6,
          new ::grpc::internal::CallbackBidiHandler< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->VehicleCommandStream(context); }));
    }
    ~WithCallbackMethod_VehicleCommandStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VehicleCommandStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::vehicle_gateway::GatewayCommand, ::vehicle_gateway::VehicleEvent>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>* VehicleCommandStream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_SendEta<WithCallbackMethod_SendStatus<WithCallbackMethod_SendArrive<WithCallbackMethod_UpdateVehicleLocation<WithCallbackMethod_TripInit<WithCallbackMethod_TripMove<WithCallbackMethod_VehicleCommandStream<Service > > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendEta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendEta() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendEta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendEta(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::EtaRequest* /*request*/, ::vehicle_gateway::EtaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SendStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendStatus() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SendStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendStatus(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::StatusRequest* /*request*/, ::vehicle_gateway::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SendArrive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendArrive() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_SendArrive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendArrive(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::ArriveRequest* /*request*/, ::vehicle_gateway::ArriveResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateVehicleLocation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateVehicleLocation() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_UpdateVehicleLocation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateVehicleLocation(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::UpdateVehicleLocationRequest* /*request*/, ::vehicle_gateway::UpdateVehicleLocationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_TripInit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_TripInit() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_TripInit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TripInit(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::TripInitRequest* /*request*/, ::vehicle_gateway::TripInitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_TripMove : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_TripMove() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_TripMove() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TripMove(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::TripMoveRequest* /*request*/, ::vehicle_gateway::TripMoveResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_VehicleCommandStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_VehicleCommandStream() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_VehicleCommandStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VehicleCommandStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::vehicle_gateway::GatewayCommand, ::vehicle_gateway::VehicleEvent>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendEta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendEta() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendEta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendEta(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::EtaRequest* /*request*/, ::vehicle_gateway::EtaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendEta(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendStatus() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SendStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendStatus(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::StatusRequest* /*request*/, ::vehicle_gateway::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendArrive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendArrive() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_SendArrive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendArrive(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::ArriveRequest* /*request*/, ::vehicle_gateway::ArriveResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendArrive(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateVehicleLocation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateVehicleLocation() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_UpdateVehicleLocation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateVehicleLocation(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::UpdateVehicleLocationRequest* /*request*/, ::vehicle_gateway::UpdateVehicleLocationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateVehicleLocation(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_TripInit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_TripInit() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_TripInit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TripInit(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::TripInitRequest* /*request*/, ::vehicle_gateway::TripInitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTripInit(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_TripMove : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_TripMove() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_TripMove() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TripMove(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::TripMoveRequest* /*request*/, ::vehicle_gateway::TripMoveResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTripMove(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_VehicleCommandStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_VehicleCommandStream() {
      ::grpc::Service::MarkMethodRaw(6);
    }
    ~WithRawMethod_VehicleCommandStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VehicleCommandStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::vehicle_gateway::GatewayCommand, ::vehicle_gateway::VehicleEvent>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVehicleCommandStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(6, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendEta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendEta() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendEta(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendEta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendEta(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::EtaRequest* /*request*/, ::vehicle_gateway::EtaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendEta(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendStatus() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendStatus(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::StatusRequest* /*request*/, ::vehicle_gateway::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendArrive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendArrive() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendArrive(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendArrive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendArrive(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::ArriveRequest* /*request*/, ::vehicle_gateway::ArriveResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendArrive(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UpdateVehicleLocation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UpdateVehicleLocation() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdateVehicleLocation(context, request, response); }));
    }
    ~WithRawCallbackMethod_UpdateVehicleLocation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateVehicleLocation(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::UpdateVehicleLocationRequest* /*request*/, ::vehicle_gateway::UpdateVehicleLocationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateVehicleLocation(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_TripInit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_TripInit() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->TripInit(context, request, response); }));
    }
    ~WithRawCallbackMethod_TripInit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TripInit(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::TripInitRequest* /*request*/, ::vehicle_gateway::TripInitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TripInit(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_TripMove : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_TripMove() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->TripMove(context, request, response); }));
    }
    ~WithRawCallbackMethod_TripMove() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TripMove(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::TripMoveRequest* /*request*/, ::vehicle_gateway::TripMoveResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TripMove(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_VehicleCommandStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_VehicleCommandStream() {
      ::grpc::Service::MarkMethodRawCallback(6,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->VehicleCommandStream(context); }));
    }
    ~WithRawCallbackMethod_VehicleCommandStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VehicleCommandStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::vehicle_gateway::GatewayCommand, ::vehicle_gateway::VehicleEvent>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* VehicleCommandStream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendEta : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendEta() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vehicle_gateway::EtaRequest, ::vehicle_gateway::EtaResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vehicle_gateway::EtaRequest, ::vehicle_gateway::EtaResponse>* streamer) {
                       return this->StreamedSendEta(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendEta() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendEta(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::EtaRequest* /*request*/, ::vehicle_gateway::EtaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendEta(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vehicle_gateway::EtaRequest,::vehicle_gateway::EtaResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendStatus() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vehicle_gateway::StatusRequest, ::vehicle_gateway::StatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vehicle_gateway::StatusRequest, ::vehicle_gateway::StatusResponse>* streamer) {
                       return this->StreamedSendStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendStatus(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::StatusRequest* /*request*/, ::vehicle_gateway::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vehicle_gateway::StatusRequest,::vehicle_gateway::StatusResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendArrive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendArrive() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vehicle_gateway::ArriveRequest, ::vehicle_gateway::ArriveResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vehicle_gateway::ArriveRequest, ::vehicle_gateway::ArriveResponse>* streamer) {
                       return this->StreamedSendArrive(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendArrive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendArrive(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::ArriveRequest* /*request*/, ::vehicle_gateway::ArriveResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendArrive(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vehicle_gateway::ArriveRequest,::vehicle_gateway::ArriveResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateVehicleLocation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdateVehicleLocation() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vehicle_gateway::UpdateVehicleLocationRequest, ::vehicle_gateway::UpdateVehicleLocationResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vehicle_gateway::UpdateVehicleLocationRequest, ::vehicle_gateway::UpdateVehicleLocationResponse>* streamer) {
                       return this->StreamedUpdateVehicleLocation(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdateVehicleLocation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateVehicleLocation(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::UpdateVehicleLocationRequest* /*request*/, ::vehicle_gateway::UpdateVehicleLocationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateVehicleLocation(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vehicle_gateway::UpdateVehicleLocationRequest,::vehicle_gateway::UpdateVehicleLocationResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_TripInit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_TripInit() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vehicle_gateway::TripInitRequest, ::vehicle_gateway::TripInitResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vehicle_gateway::TripInitRequest, ::vehicle_gateway::TripInitResponse>* streamer) {
                       return this->StreamedTripInit(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_TripInit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status TripInit(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::TripInitRequest* /*request*/, ::vehicle_gateway::TripInitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedTripInit(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vehicle_gateway::TripInitRequest,::vehicle_gateway::TripInitResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_TripMove : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_TripMove() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vehicle_gateway::TripMoveRequest, ::vehicle_gateway::TripMoveResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vehicle_gateway::TripMoveRequest, ::vehicle_gateway::TripMoveResponse>* streamer) {
                       return this->StreamedTripMove(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_TripMove() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status TripMove(::grpc::ServerContext* /*context*/, const ::vehicle_gateway::TripMoveRequest* /*request*/, ::vehicle_gateway::TripMoveResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedTripMove(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vehicle_gateway::TripMoveRequest,::vehicle_gateway::TripMoveResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendEta<WithStreamedUnaryMethod_SendStatus<WithStreamedUnaryMethod_SendArrive<WithStreamedUnaryMethod_UpdateVehicleLocation<WithStreamedUnaryMethod_TripInit<WithStreamedUnaryMethod_TripMove<Service > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendEta<WithStreamedUnaryMethod_SendStatus<WithStreamedUnaryMethod_SendArrive<WithStreamedUnaryMethod_UpdateVehicleLocation<WithStreamedUnaryMethod_TripInit<WithStreamedUnaryMethod_TripMove<Service > > > > > > StreamedService;
};

}  // namespace vehicle_gateway


#endif  // GRPC_vehicle_5fgateway_2eproto__INCLUDED
