// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vehicle_gateway.proto

#include "vehicle_gateway.pb.h"
#include "vehicle_gateway.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace vehicle_gateway {

static const char* VehicleGateway_method_names[] = {
  "/vehicle_gateway.VehicleGateway/SendEta",
  "/vehicle_gateway.VehicleGateway/SendStatus",
  "/vehicle_gateway.VehicleGateway/SendArrive",
  "/vehicle_gateway.VehicleGateway/UpdateVehicleLocation",
  "/vehicle_gateway.VehicleGateway/TripInit",
  "/vehicle_gateway.VehicleGateway/TripMove",
  "/vehicle_gateway.VehicleGateway/VehicleCommandStream",
};

std::unique_ptr< VehicleGateway::Stub> VehicleGateway::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VehicleGateway::Stub> stub(new VehicleGateway::Stub(channel, options));
  return stub;
}

VehicleGateway::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendEta_(VehicleGateway_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendStatus_(VehicleGateway_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendArrive_(VehicleGateway_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateVehicleLocation_(VehicleGateway_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_TripInit_(VehicleGateway_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_TripMove_(VehicleGateway_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_VehicleCommandStream_(VehicleGateway_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status VehicleGateway::Stub::SendEta(::grpc::ClientContext* context, const ::vehicle_gateway::EtaRequest& request, ::vehicle_gateway::EtaResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vehicle_gateway::EtaRequest, ::vehicle_gateway::EtaResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendEta_, context, request, response);
}

void VehicleGateway::Stub::async::SendEta(::grpc::ClientContext* context, const ::vehicle_gateway::EtaRequest* request, ::vehicle_gateway::EtaResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vehicle_gateway::EtaRequest, ::vehicle_gateway::EtaResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendEta_, context, request, response, std::move(f));
}

void VehicleGateway::Stub::async::SendEta(::grpc::ClientContext* context, const ::vehicle_gateway::EtaRequest* request, ::vehicle_gateway::EtaResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendEta_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vehicle_gateway::EtaResponse>* VehicleGateway::Stub::PrepareAsyncSendEtaRaw(::grpc::ClientContext* context, const ::vehicle_gateway::EtaRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vehicle_gateway::EtaResponse, ::vehicle_gateway::EtaRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendEta_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vehicle_gateway::EtaResponse>* VehicleGateway::Stub::AsyncSendEtaRaw(::grpc::ClientContext* context, const ::vehicle_gateway::EtaRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendEtaRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status VehicleGateway::Stub::SendStatus(::grpc::ClientContext* context, const ::vehicle_gateway::StatusRequest& request, ::vehicle_gateway::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vehicle_gateway::StatusRequest, ::vehicle_gateway::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendStatus_, context, request, response);
}

void VehicleGateway::Stub::async::SendStatus(::grpc::ClientContext* context, const ::vehicle_gateway::StatusRequest* request, ::vehicle_gateway::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vehicle_gateway::StatusRequest, ::vehicle_gateway::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendStatus_, context, request, response, std::move(f));
}

void VehicleGateway::Stub::async::SendStatus(::grpc::ClientContext* context, const ::vehicle_gateway::StatusRequest* request, ::vehicle_gateway::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vehicle_gateway::StatusResponse>* VehicleGateway::Stub::PrepareAsyncSendStatusRaw(::grpc::ClientContext* context, const ::vehicle_gateway::StatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vehicle_gateway::StatusResponse, ::vehicle_gateway::StatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vehicle_gateway::StatusResponse>* VehicleGateway::Stub::AsyncSendStatusRaw(::grpc::ClientContext* context, const ::vehicle_gateway::StatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status VehicleGateway::Stub::SendArrive(::grpc::ClientContext* context, const ::vehicle_gateway::ArriveRequest& request, ::vehicle_gateway::ArriveResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vehicle_gateway::ArriveRequest, ::vehicle_gateway::ArriveResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendArrive_, context, request, response);
}

void VehicleGateway::Stub::async::SendArrive(::grpc::ClientContext* context, const ::vehicle_gateway::ArriveRequest* request, ::vehicle_gateway::ArriveResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vehicle_gateway::ArriveRequest, ::vehicle_gateway::ArriveResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendArrive_, context, request, response, std::move(f));
}

void VehicleGateway::Stub::async::SendArrive(::grpc::ClientContext* context, const ::vehicle_gateway::ArriveRequest* request, ::vehicle_gateway::ArriveResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendArrive_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vehicle_gateway::ArriveResponse>* VehicleGateway::Stub::PrepareAsyncSendArriveRaw(::grpc::ClientContext* context, const ::vehicle_gateway::ArriveRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vehicle_gateway::ArriveResponse, ::vehicle_gateway::ArriveRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendArrive_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vehicle_gateway::ArriveResponse>* VehicleGateway::Stub::AsyncSendArriveRaw(::grpc::ClientContext* context, const ::vehicle_gateway::ArriveRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendArriveRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status VehicleGateway::Stub::UpdateVehicleLocation(::grpc::ClientContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest& request, ::vehicle_gateway::UpdateVehicleLocationResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vehicle_gateway::UpdateVehicleLocationRequest, ::vehicle_gateway::UpdateVehicleLocationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateVehicleLocation_, context, request, response);
}

void VehicleGateway::Stub::async::UpdateVehicleLocation(::grpc::ClientContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest* request, ::vehicle_gateway::UpdateVehicleLocationResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vehicle_gateway::UpdateVehicleLocationRequest, ::vehicle_gateway::UpdateVehicleLocationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateVehicleLocation_, context, request, response, std::move(f));
}

void VehicleGateway::Stub::async::UpdateVehicleLocation(::grpc::ClientContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest* request, ::vehicle_gateway::UpdateVehicleLocationResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateVehicleLocation_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vehicle_gateway::UpdateVehicleLocationResponse>* VehicleGateway::Stub::PrepareAsyncUpdateVehicleLocationRaw(::grpc::ClientContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vehicle_gateway::UpdateVehicleLocationResponse, ::vehicle_gateway::UpdateVehicleLocationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateVehicleLocation_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vehicle_gateway::UpdateVehicleLocationResponse>* VehicleGateway::Stub::AsyncUpdateVehicleLocationRaw(::grpc::ClientContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateVehicleLocationRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status VehicleGateway::Stub::TripInit(::grpc::ClientContext* context, const ::vehicle_gateway::TripInitRequest& request, ::vehicle_gateway::TripInitResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vehicle_gateway::TripInitRequest, ::vehicle_gateway::TripInitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_TripInit_, context, request, response);
}

void VehicleGateway::Stub::async::TripInit(::grpc::ClientContext* context, const ::vehicle_gateway::TripInitRequest* request, ::vehicle_gateway::TripInitResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vehicle_gateway::TripInitRequest, ::vehicle_gateway::TripInitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TripInit_, context, request, response, std::move(f));
}

void VehicleGateway::Stub::async::TripInit(::grpc::ClientContext* context, const ::vehicle_gateway::TripInitRequest* request, ::vehicle_gateway::TripInitResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TripInit_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vehicle_gateway::TripInitResponse>* VehicleGateway::Stub::PrepareAsyncTripInitRaw(::grpc::ClientContext* context, const ::vehicle_gateway::TripInitRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vehicle_gateway::TripInitResponse, ::vehicle_gateway::TripInitRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_TripInit_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vehicle_gateway::TripInitResponse>* VehicleGateway::Stub::AsyncTripInitRaw(::grpc::ClientContext* context, const ::vehicle_gateway::TripInitRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTripInitRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status VehicleGateway::Stub::TripMove(::grpc::ClientContext* context, const ::vehicle_gateway::TripMoveRequest& request, ::vehicle_gateway::TripMoveResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vehicle_gateway::TripMoveRequest, ::vehicle_gateway::TripMoveResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_TripMove_, context, request, response);
}

void VehicleGateway::Stub::async::TripMove(::grpc::ClientContext* context, const ::vehicle_gateway::TripMoveRequest* request, ::vehicle_gateway::TripMoveResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vehicle_gateway::TripMoveRequest, ::vehicle_gateway::TripMoveResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TripMove_, context, request, response, std::move(f));
}

void VehicleGateway::Stub::async::TripMove(::grpc::ClientContext* context, const ::vehicle_gateway::TripMoveRequest* request, ::vehicle_gateway::TripMoveResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TripMove_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vehicle_gateway::TripMoveResponse>* VehicleGateway::Stub::PrepareAsyncTripMoveRaw(::grpc::ClientContext* context, const ::vehicle_gateway::TripMoveRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vehicle_gateway::TripMoveResponse, ::vehicle_gateway::TripMoveRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_TripMove_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vehicle_gateway::TripMoveResponse>* VehicleGateway::Stub::AsyncTripMoveRaw(::grpc::ClientContext* context, const ::vehicle_gateway::TripMoveRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTripMoveRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>* VehicleGateway::Stub::VehicleCommandStreamRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>::Create(channel_.get(), rpcmethod_VehicleCommandStream_, context);
}

void VehicleGateway::Stub::async::VehicleCommandStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::vehicle_gateway::VehicleEvent,::vehicle_gateway::GatewayCommand>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::vehicle_gateway::VehicleEvent,::vehicle_gateway::GatewayCommand>::Create(stub_->channel_.get(), stub_->rpcmethod_VehicleCommandStream_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>* VehicleGateway::Stub::AsyncVehicleCommandStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>::Create(channel_.get(), cq, rpcmethod_VehicleCommandStream_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>* VehicleGateway::Stub::PrepareAsyncVehicleCommandStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>::Create(channel_.get(), cq, rpcmethod_VehicleCommandStream_, context, false, nullptr);
}

VehicleGateway::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleGateway_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleGateway::Service, ::vehicle_gateway::EtaRequest, ::vehicle_gateway::EtaResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VehicleGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vehicle_gateway::EtaRequest* req,
             ::vehicle_gateway::EtaResponse* resp) {
               return service->SendEta(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleGateway_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleGateway::Service, ::vehicle_gateway::StatusRequest, ::vehicle_gateway::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VehicleGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vehicle_gateway::StatusRequest* req,
             ::vehicle_gateway::StatusResponse* resp) {
               return service->SendStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleGateway_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleGateway::Service, ::vehicle_gateway::ArriveRequest, ::vehicle_gateway::ArriveResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VehicleGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vehicle_gateway::ArriveRequest* req,
             ::vehicle_gateway::ArriveResponse* resp) {
               return service->SendArrive(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleGateway_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleGateway::Service, ::vehicle_gateway::UpdateVehicleLocationRequest, ::vehicle_gateway::UpdateVehicleLocationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VehicleGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vehicle_gateway::UpdateVehicleLocationRequest* req,
             ::vehicle_gateway::UpdateVehicleLocationResponse* resp) {
               return service->UpdateVehicleLocation(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleGateway_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleGateway::Service, ::vehicle_gateway::TripInitRequest, ::vehicle_gateway::TripInitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VehicleGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vehicle_gateway::TripInitRequest* req,
             ::vehicle_gateway::TripInitResponse* resp) {
               return service->TripInit(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleGateway_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VehicleGateway::Service, ::vehicle_gateway::TripMoveRequest, ::vehicle_gateway::TripMoveResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VehicleGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vehicle_gateway::TripMoveRequest* req,
             ::vehicle_gateway::TripMoveResponse* resp) {
               return service->TripMove(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VehicleGateway_method_names[6],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< VehicleGateway::Service, ::vehicle_gateway::VehicleEvent, ::vehicle_gateway::GatewayCommand>(
          [](VehicleGateway::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::vehicle_gateway::GatewayCommand,
             ::vehicle_gateway::VehicleEvent>* stream) {
               return service->VehicleCommandStream(ctx, stream);
             }, this)));
}

VehicleGateway::Service::~Service() {
}

::grpc::Status VehicleGateway::Service::SendEta(::grpc::ServerContext* context, const ::vehicle_gateway::EtaRequest* request, ::vehicle_gateway::EtaResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleGateway::Service::SendStatus(::grpc::ServerContext* context, const ::vehicle_gateway::StatusRequest* request, ::vehicle_gateway::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleGateway::Service::SendArrive(::grpc::ServerContext* context, const ::vehicle_gateway::ArriveRequest* request, ::vehicle_gateway::ArriveResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleGateway::Service::UpdateVehicleLocation(::grpc::ServerContext* context, const ::vehicle_gateway::UpdateVehicleLocationRequest* request, ::vehicle_gateway::UpdateVehicleLocationResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleGateway::Service::TripInit(::grpc::ServerContext* context, const ::vehicle_gateway::TripInitRequest* request, ::vehicle_gateway::TripInitResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleGateway::Service::TripMove(::grpc::ServerContext* context, const ::vehicle_gateway::TripMoveRequest* request, ::vehicle_gateway::TripMoveResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VehicleGateway::Service::VehicleCommandStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::vehicle_gateway::GatewayCommand, ::vehicle_gateway::VehicleEvent>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace vehicle_gateway

